### ISSUE TITLE
Error 1.16.5

### ISSUE THREAD

**Issue by nejmik242** [JoseGamerPT/RealMines#3]
[18:52:37] [Server thread/INFO]: Nejmik242 issued server command: /mine delete test
[18:52:37] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[18:52:37] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:52:37] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[18:52:37] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[18:52:37] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[18:52:37] [Server thread/WARN]: 	at me.mattstudios.mf.base.CommandHandler.executeCommand(CommandHandler.java:303)
[18:52:37] [Server thread/WARN]: 	at me.mattstudios.mf.base.CommandHandler.execute(CommandHandler.java:218)
[18:52:37] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[18:52:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2306)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2121)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2074)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1336)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1329)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1305)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1149)
[18:52:37] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[18:52:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[18:52:37] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[18:52:37] [Server thread/WARN]: 	at josegamerpt.realmines.managers.MineManager.unregisterMine(MineManager.java:46)
[18:52:37] [Server thread/WARN]: 	at josegamerpt.realmines.managers.MineManager.deleteMine(MineManager.java:303)
[18:52:37] [Server thread/WARN]: 	at josegamerpt.realmines.commands.MineCMD.deletecmd(MineCMD.java:174)
[18:52:37] [Server thread/WARN]: 	... 25 more
[18:52:49] [Server thread/INFO]: [RealMines] Mine test just reset.

Version: This server is running Purpur version git-Purpur-1111 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
You are 15 version(s) behind

**Comment by JoseGamerPT** [comment]
Can you describe what were you trying to do? Thanks

**Comment by nejmik242** [comment]
Yes, I created a mine and removed it
