### ISSUE TITLE
null world 

### ISSUE THREAD

**Issue by zsak1** [JoseGamerPT/RealMines#9]
[09:47:14 ERROR]: Error occurred while enabling RealMines v05-10-2022 Build 1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "org.bukkit.Location.getWorld()" is null
        at josegamerpt.realmines.mines.components.MineCuboid.<init>(MineCuboid.java:40) ~[?:?]
        at josegamerpt.realmines.mines.mine.BlockMine.setPOS(BlockMine.java:196) ~[?:?]
        at josegamerpt.realmines.mines.mine.BlockMine.<init>(BlockMine.java:64) ~[?:?]
        at josegamerpt.realmines.managers.MineManager.loadMines(MineManager.java:124) ~[?:?]
        at josegamerpt.realmines.RealMines.onEnable(RealMines.java:156) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:596) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:309) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Purpur-1171]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:293) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[09:47:14 INFO]: [RealMines] Disabling RealMines v05-10-2022 Build 1

**Comment by JoseGamerPT** [comment]
More context needed. When does this happen? Is the world loaded?

**Comment by neziw** [comment]
> More context needed. When does this happen? Is the world loaded?

The exception indicates that the world is null so the only possible problem is that the world has not been loaded or it had exists before. Otherwise, this exception will not happen.

@zsak1 - You should check for other world-related exceptions when engine is loading worlds and solve them yourself.
